from typing import Any, Optional


class SerializableType:
    def _serialize(self): ...
    @classmethod
    def _deserialize(cls, value): ...


class SerializationStrategy:
    def _serialize(self, value): ...
    def _deserialize(self, value): ...


class RoundedDecimal(SerializationStrategy):
    exp: Any = ...
    rounding: Any = ...
    def __init__(self, places: Optional[Any] = ..., rounding: Optional[Any] = ...) -> None: ...
